---
components:
  schemas:
    AiCluster
      "$ref": "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/AiCluster/model.yaml#/AiCluster
    GpuDevice
      "$ref": "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/GpuDevice/model.yaml#/GpuDevice
    AiNode
      "$ref": "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/AiNode/model.yaml#/AiNode
info:
  description: >+
openapi: "3.0.0"
paths:
  /ngsi-ld/v1/entities:
    get:
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters:
        - in: query
          name: type
          required: true
          schema:
            enum:
              - TrafficFlowObserved
            type: string
      responses:
        "200":
          content:
            "application/ld+json":
              examples:
                keyvalues:
                  summary: "Key-Values Pairs"
                  value:
                    - "$ref": "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/AiCluster/examples/example.json"
                    - "$ref": "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/GpuDevice/examples/example.json"
                    - "$ref": "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/AiNode/examples/example.json"
                normalized:
                  summary: "Normalized NGSI-LD"
                  value:
                    - $ref: "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/AiCluster/examples/example-normalized.json"
                    - $ref: "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/GpuDevice/examples/example-normalized.json"
                    - $ref: "https://raw.githubusercontent.com/OCP-on-NERC/ai-telemetry-static/main/fiware/AiNode/examples/example-normalized.json"
          description: OK
      tags:
        - ngsi-ld
tags:
  description: "NGSI-LD Linked-data Format"
  name: ngsi-ld
